
/*** !!! Autogenerated from source/mtx/AstralFactory.mtx !!! ***/

#ifndef ASTRAL_ASTRALFACTORY_H
#define ASTRAL_ASTRALFACTORY_H

#include "astral.h"

#include <openxds.adt.h>
#include <openxds.io.h>
#include <openxds/Object.h>

class AstralFactory : openxds::Object
{
public:
	static astral::Astral*
	createAstral(
		const openxds::adt::IList<openxds::io::Path>& pathList,
		const char*                                   extension
	);

	static astral::AstralExport*
	createAstralExport(
		const openxds::adt::IList<openxds::io::Path>& pathList,
		const char*                                   extension
	);
};

#endif
